--
-- PostgreSQL database dump
--

\restrict saOqgpNiyIdJo9e5Ju5bRw6ljfZiNNUZjGECjhROd7dDVzkxF7YIWKOKMFktDKc

-- Dumped from database version 16.15
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO daire;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO daire;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO daire;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO daire;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO daire;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO daire;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_aireputationresult; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_aireputationresult (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    reputation character varying(30) NOT NULL,
    score numeric(7,4) NOT NULL,
    risk_level character varying(30) NOT NULL,
    behavior_summary text NOT NULL,
    model_version character varying(64) NOT NULL,
    raw_result jsonb NOT NULL,
    assessment_id bigint NOT NULL
);


ALTER TABLE public.core_aireputationresult OWNER TO daire;

--
-- Name: core_aireputationresult_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_aireputationresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_aireputationresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_assessment; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_assessment (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    assessment_reference character varying(64) NOT NULL,
    reputation character varying(30) NOT NULL,
    reputation_score numeric(5,4),
    risk_level character varying(20) NOT NULL,
    behavior_summary text NOT NULL,
    credit_score smallint,
    ruleset_version character varying(64) NOT NULL,
    model_version character varying(64) NOT NULL,
    blockchain_transaction_hash character varying(255) NOT NULL,
    blockchain_block_number bigint,
    verification_status character varying(30) NOT NULL,
    borrower_id bigint NOT NULL,
    CONSTRAINT core_assessment_blockchain_block_number_check CHECK ((blockchain_block_number >= 0)),
    CONSTRAINT core_assessment_credit_score_check CHECK ((credit_score >= 0))
);


ALTER TABLE public.core_assessment OWNER TO daire;

--
-- Name: core_assessment_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_assessment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_assessment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_blockchaintransaction; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_blockchaintransaction (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    transaction_hash character varying(255) NOT NULL,
    network character varying(100) NOT NULL,
    block_number bigint,
    status character varying(30) NOT NULL,
    verification_data jsonb NOT NULL,
    assessment_id bigint NOT NULL,
    CONSTRAINT core_blockchaintransaction_block_number_check CHECK ((block_number >= 0))
);


ALTER TABLE public.core_blockchaintransaction OWNER TO daire;

--
-- Name: core_blockchaintransaction_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_blockchaintransaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_blockchaintransaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_borrower; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_borrower (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    borrower_reference character varying(64) NOT NULL,
    customer_id character varying(64) NOT NULL,
    age smallint,
    gender character varying(20) NOT NULL,
    employment_status character varying(50) NOT NULL,
    income numeric(16,4),
    business_information jsonb NOT NULL,
    account_information jsonb NOT NULL,
    CONSTRAINT core_borrower_age_check CHECK ((age >= 0))
);


ALTER TABLE public.core_borrower OWNER TO daire;

--
-- Name: core_borrower_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_borrower ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_borrower_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_borroweraccount; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_borroweraccount (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    account_reference character varying(128) NOT NULL,
    account_name character varying(255) NOT NULL,
    customer_id character varying(64) NOT NULL,
    metadata jsonb NOT NULL,
    borrower_id bigint NOT NULL,
    lender_id bigint NOT NULL
);


ALTER TABLE public.core_borroweraccount OWNER TO daire;

--
-- Name: core_borroweraccount_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_borroweraccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_borroweraccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_borrowerfinancialprofile; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_borrowerfinancialprofile (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    transaction_frequency integer NOT NULL,
    income_frequency integer NOT NULL,
    cash_flow_patterns jsonb NOT NULL,
    savings numeric(18,4) NOT NULL,
    account_activity jsonb NOT NULL,
    active_loans integer NOT NULL,
    total_outstanding_debt numeric(18,4) NOT NULL,
    monthly_repayment numeric(18,4) NOT NULL,
    previous_loans integer NOT NULL,
    debt_to_income_ratio numeric(9,4) NOT NULL,
    borrower_id bigint NOT NULL,
    CONSTRAINT core_borrowerfinancialprofile_active_loans_check CHECK ((active_loans >= 0)),
    CONSTRAINT core_borrowerfinancialprofile_income_frequency_check CHECK ((income_frequency >= 0)),
    CONSTRAINT core_borrowerfinancialprofile_previous_loans_check CHECK ((previous_loans >= 0)),
    CONSTRAINT core_borrowerfinancialprofile_transaction_frequency_check CHECK ((transaction_frequency >= 0))
);


ALTER TABLE public.core_borrowerfinancialprofile OWNER TO daire;

--
-- Name: core_borrowerfinancialprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_borrowerfinancialprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_borrowerfinancialprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_borrowerloan; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_borrowerloan (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    loan_id character varying(128) NOT NULL,
    loan_amount numeric(18,4) NOT NULL,
    loan_date date,
    loan_duration_months integer NOT NULL,
    interest_rate numeric(8,4) NOT NULL,
    outstanding_balance numeric(18,4) NOT NULL,
    status character varying(30) NOT NULL,
    borrower_id bigint NOT NULL,
    lender_id bigint NOT NULL,
    source_account_id bigint,
    CONSTRAINT core_borrowerloan_loan_duration_months_check CHECK ((loan_duration_months >= 0))
);


ALTER TABLE public.core_borrowerloan OWNER TO daire;

--
-- Name: core_borrowerloan_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_borrowerloan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_borrowerloan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_consent; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_consent (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    consent_id character varying(64) NOT NULL,
    purpose character varying(255) NOT NULL,
    granted_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    status character varying(10) NOT NULL,
    borrower_id bigint NOT NULL,
    lender_id bigint NOT NULL
);


ALTER TABLE public.core_consent OWNER TO daire;

--
-- Name: core_consent_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_consent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_consent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_creditfeature; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_creditfeature (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(100) NOT NULL,
    value numeric(20,4) NOT NULL,
    feature_version character varying(64) NOT NULL,
    profile_id bigint NOT NULL
);


ALTER TABLE public.core_creditfeature OWNER TO daire;

--
-- Name: core_creditfeature_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_creditfeature ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_creditfeature_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_creditprofile; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_creditprofile (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    profile_data jsonb NOT NULL,
    source_version character varying(64) NOT NULL,
    borrower_id bigint NOT NULL,
    integration_request_id bigint
);


ALTER TABLE public.core_creditprofile OWNER TO daire;

--
-- Name: core_creditprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_creditprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_creditprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_dataexchange; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_dataexchange (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    system character varying(20) NOT NULL,
    direction character varying(10) NOT NULL,
    operation character varying(100) NOT NULL,
    status character varying(10) NOT NULL,
    fields_sent jsonb NOT NULL,
    payload jsonb NOT NULL,
    response jsonb NOT NULL,
    error_message text NOT NULL,
    assessment_id bigint,
    borrower_id bigint,
    lender_id bigint,
    policy_id bigint
);


ALTER TABLE public.core_dataexchange OWNER TO daire;

--
-- Name: core_dataexchange_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_dataexchange ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_dataexchange_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_dataroutingpolicy; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_dataroutingpolicy (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    policy_id character varying(64) NOT NULL,
    name character varying(255) NOT NULL,
    ai_fields jsonb NOT NULL,
    blockchain_fields jsonb NOT NULL,
    active boolean NOT NULL,
    version character varying(64) NOT NULL,
    lender_fields jsonb NOT NULL
);


ALTER TABLE public.core_dataroutingpolicy OWNER TO daire;

--
-- Name: core_dataroutingpolicy_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_dataroutingpolicy ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_dataroutingpolicy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_integrationrequest; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_integrationrequest (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    request_reference uuid NOT NULL,
    status character varying(12) NOT NULL,
    error_message text NOT NULL,
    raw_payload jsonb NOT NULL,
    borrower_id bigint NOT NULL,
    consent_id bigint NOT NULL,
    lender_id bigint NOT NULL
);


ALTER TABLE public.core_integrationrequest OWNER TO daire;

--
-- Name: core_integrationrequest_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_integrationrequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_integrationrequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_lender; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_lender (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lender_id character varying(64) NOT NULL,
    institution_name character varying(255) NOT NULL,
    institution_type character varying(100) NOT NULL,
    api_base_url character varying(200) NOT NULL,
    api_status character varying(20) NOT NULL,
    authentication_method character varying(50) NOT NULL
);


ALTER TABLE public.core_lender OWNER TO daire;

--
-- Name: core_lender_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_lender ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_lender_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_repaymentrecord; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_repaymentrecord (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    repayment_amount numeric(18,4) NOT NULL,
    repayment_date date,
    due_date date,
    days_overdue integer NOT NULL,
    missed_payments integer NOT NULL,
    late_payments integer NOT NULL,
    default_status character varying(20) NOT NULL,
    borrower_id bigint NOT NULL,
    lender_id bigint NOT NULL,
    loan_id bigint NOT NULL,
    CONSTRAINT core_repaymentrecord_days_overdue_check CHECK ((days_overdue >= 0)),
    CONSTRAINT core_repaymentrecord_late_payments_check CHECK ((late_payments >= 0)),
    CONSTRAINT core_repaymentrecord_missed_payments_check CHECK ((missed_payments >= 0))
);


ALTER TABLE public.core_repaymentrecord OWNER TO daire;

--
-- Name: core_repaymentrecord_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_repaymentrecord ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_repaymentrecord_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_smartcontractresult; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.core_smartcontractresult (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    credit_score smallint NOT NULL,
    ruleset_version character varying(64) NOT NULL,
    contract_address character varying(255) NOT NULL,
    raw_result jsonb NOT NULL,
    assessment_id bigint NOT NULL,
    CONSTRAINT core_smartcontractresult_credit_score_check CHECK ((credit_score >= 0))
);


ALTER TABLE public.core_smartcontractresult OWNER TO daire;

--
-- Name: core_smartcontractresult_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.core_smartcontractresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_smartcontractresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO daire;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO daire;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO daire;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: daire
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: daire
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO daire;

--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add borrower	7	add_borrower
26	Can change borrower	7	change_borrower
27	Can delete borrower	7	delete_borrower
28	Can view borrower	7	view_borrower
29	Can add lender	8	add_lender
30	Can change lender	8	change_lender
31	Can delete lender	8	delete_lender
32	Can view lender	8	view_lender
33	Can add assessment	9	add_assessment
34	Can change assessment	9	change_assessment
35	Can delete assessment	9	delete_assessment
36	Can view assessment	9	view_assessment
37	Can add consent	10	add_consent
38	Can change consent	10	change_consent
39	Can delete consent	10	delete_consent
40	Can view consent	10	view_consent
41	Can add integration request	11	add_integrationrequest
42	Can change integration request	11	change_integrationrequest
43	Can delete integration request	11	delete_integrationrequest
44	Can view integration request	11	view_integrationrequest
45	Can add ai reputation result	12	add_aireputationresult
46	Can change ai reputation result	12	change_aireputationresult
47	Can delete ai reputation result	12	delete_aireputationresult
48	Can view ai reputation result	12	view_aireputationresult
49	Can add blockchain transaction	13	add_blockchaintransaction
50	Can change blockchain transaction	13	change_blockchaintransaction
51	Can delete blockchain transaction	13	delete_blockchaintransaction
52	Can view blockchain transaction	13	view_blockchaintransaction
53	Can add credit profile	14	add_creditprofile
54	Can change credit profile	14	change_creditprofile
55	Can delete credit profile	14	delete_creditprofile
56	Can view credit profile	14	view_creditprofile
57	Can add smart contract result	15	add_smartcontractresult
58	Can change smart contract result	15	change_smartcontractresult
59	Can delete smart contract result	15	delete_smartcontractresult
60	Can view smart contract result	15	view_smartcontractresult
61	Can add credit feature	16	add_creditfeature
62	Can change credit feature	16	change_creditfeature
63	Can delete credit feature	16	delete_creditfeature
64	Can view credit feature	16	view_creditfeature
65	Can add borrower account	17	add_borroweraccount
66	Can change borrower account	17	change_borroweraccount
67	Can delete borrower account	17	delete_borroweraccount
68	Can view borrower account	17	view_borroweraccount
69	Can add borrower loan	18	add_borrowerloan
70	Can change borrower loan	18	change_borrowerloan
71	Can delete borrower loan	18	delete_borrowerloan
72	Can view borrower loan	18	view_borrowerloan
73	Can add repayment record	19	add_repaymentrecord
74	Can change repayment record	19	change_repaymentrecord
75	Can delete repayment record	19	delete_repaymentrecord
76	Can view repayment record	19	view_repaymentrecord
77	Can add borrower financial profile	20	add_borrowerfinancialprofile
78	Can change borrower financial profile	20	change_borrowerfinancialprofile
79	Can delete borrower financial profile	20	delete_borrowerfinancialprofile
80	Can view borrower financial profile	20	view_borrowerfinancialprofile
81	Can add data routing policy	21	add_dataroutingpolicy
82	Can change data routing policy	21	change_dataroutingpolicy
83	Can delete data routing policy	21	delete_dataroutingpolicy
84	Can view data routing policy	21	view_dataroutingpolicy
85	Can add data exchange	22	add_dataexchange
86	Can change data exchange	22	change_dataexchange
87	Can delete data exchange	22	delete_dataexchange
88	Can view data exchange	22	view_dataexchange
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: core_aireputationresult; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_aireputationresult (id, created_at, updated_at, reputation, score, risk_level, behavior_summary, model_version, raw_result, assessment_id) FROM stdin;
\.


--
-- Data for Name: core_assessment; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_assessment (id, created_at, updated_at, assessment_reference, reputation, reputation_score, risk_level, behavior_summary, credit_score, ruleset_version, model_version, blockchain_transaction_hash, blockchain_block_number, verification_status, borrower_id) FROM stdin;
\.


--
-- Data for Name: core_blockchaintransaction; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_blockchaintransaction (id, created_at, updated_at, transaction_hash, network, block_number, status, verification_data, assessment_id) FROM stdin;
\.


--
-- Data for Name: core_borrower; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_borrower (id, created_at, updated_at, borrower_reference, customer_id, age, gender, employment_status, income, business_information, account_information) FROM stdin;
\.


--
-- Data for Name: core_borroweraccount; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_borroweraccount (id, created_at, updated_at, account_reference, account_name, customer_id, metadata, borrower_id, lender_id) FROM stdin;
\.


--
-- Data for Name: core_borrowerfinancialprofile; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_borrowerfinancialprofile (id, created_at, updated_at, transaction_frequency, income_frequency, cash_flow_patterns, savings, account_activity, active_loans, total_outstanding_debt, monthly_repayment, previous_loans, debt_to_income_ratio, borrower_id) FROM stdin;
\.


--
-- Data for Name: core_borrowerloan; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_borrowerloan (id, created_at, updated_at, loan_id, loan_amount, loan_date, loan_duration_months, interest_rate, outstanding_balance, status, borrower_id, lender_id, source_account_id) FROM stdin;
\.


--
-- Data for Name: core_consent; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_consent (id, created_at, updated_at, consent_id, purpose, granted_at, expires_at, status, borrower_id, lender_id) FROM stdin;
\.


--
-- Data for Name: core_creditfeature; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_creditfeature (id, created_at, updated_at, name, value, feature_version, profile_id) FROM stdin;
\.


--
-- Data for Name: core_creditprofile; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_creditprofile (id, created_at, updated_at, profile_data, source_version, borrower_id, integration_request_id) FROM stdin;
\.


--
-- Data for Name: core_dataexchange; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_dataexchange (id, created_at, updated_at, system, direction, operation, status, fields_sent, payload, response, error_message, assessment_id, borrower_id, lender_id, policy_id) FROM stdin;
\.


--
-- Data for Name: core_dataroutingpolicy; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_dataroutingpolicy (id, created_at, updated_at, policy_id, name, ai_fields, blockchain_fields, active, version, lender_fields) FROM stdin;
1	2026-09-16 04:30:02.478759+00	2026-09-16 04:30:02.478785+00	DEFAULT-CREDIT-ROUTING	Default credit scoring policy	["active_loan_count", "completed_loan_count", "defaulted_loan_count", "total_outstanding_debt", "on_time_payment_ratio", "missed_payment_count", "late_payment_count", "max_days_overdue", "transaction_frequency", "income_frequency", "balance_stability"]	["active_loan_count", "completed_loan_count", "defaulted_loan_count", "total_outstanding_debt", "on_time_payment_ratio", "missed_payment_count", "late_payment_count", "max_days_overdue"]	t	1.0.0	["borrower_reference", "customer_id", "age", "gender", "employment_status", "income", "business_information", "account_information", "account_reference", "account_name", "transaction_frequency", "income_frequency", "savings", "cash_flow_patterns", "account_activity", "loans"]
\.


--
-- Data for Name: core_integrationrequest; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_integrationrequest (id, created_at, updated_at, request_reference, status, error_message, raw_payload, borrower_id, consent_id, lender_id) FROM stdin;
\.


--
-- Data for Name: core_lender; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_lender (id, created_at, updated_at, lender_id, institution_name, institution_type, api_base_url, api_status, authentication_method) FROM stdin;
\.


--
-- Data for Name: core_repaymentrecord; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_repaymentrecord (id, created_at, updated_at, repayment_amount, repayment_date, due_date, days_overdue, missed_payments, late_payments, default_status, borrower_id, lender_id, loan_id) FROM stdin;
\.


--
-- Data for Name: core_smartcontractresult; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.core_smartcontractresult (id, created_at, updated_at, credit_score, ruleset_version, contract_address, raw_result, assessment_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	core	borrower
8	core	lender
9	core	assessment
10	core	consent
11	core	integrationrequest
12	core	aireputationresult
13	core	blockchaintransaction
14	core	creditprofile
15	core	smartcontractresult
16	core	creditfeature
17	core	borroweraccount
18	core	borrowerloan
19	core	repaymentrecord
20	core	borrowerfinancialprofile
21	core	dataroutingpolicy
22	core	dataexchange
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-16 04:29:58.22608+00
2	auth	0001_initial	2026-09-16 04:29:59.166425+00
3	admin	0001_initial	2026-09-16 04:29:59.35835+00
4	admin	0002_logentry_remove_auto_add	2026-09-16 04:29:59.385197+00
5	admin	0003_logentry_add_action_flag_choices	2026-09-16 04:29:59.408878+00
6	contenttypes	0002_remove_content_type_name	2026-09-16 04:29:59.433957+00
7	auth	0002_alter_permission_name_max_length	2026-09-16 04:29:59.445826+00
8	auth	0003_alter_user_email_max_length	2026-09-16 04:29:59.452974+00
9	auth	0004_alter_user_username_opts	2026-09-16 04:29:59.460787+00
10	auth	0005_alter_user_last_login_null	2026-09-16 04:29:59.469795+00
11	auth	0006_require_contenttypes_0002	2026-09-16 04:29:59.47434+00
12	auth	0007_alter_validators_add_error_messages	2026-09-16 04:29:59.4859+00
13	auth	0008_alter_user_username_max_length	2026-09-16 04:29:59.529654+00
14	auth	0009_alter_user_last_name_max_length	2026-09-16 04:29:59.545288+00
15	auth	0010_alter_group_name_max_length	2026-09-16 04:29:59.555386+00
16	auth	0011_update_proxy_permissions	2026-09-16 04:29:59.569946+00
17	auth	0012_alter_user_first_name_max_length	2026-09-16 04:29:59.664997+00
18	core	0001_initial	2026-09-16 04:30:00.560238+00
19	core	0002_aireputationresult_blockchaintransaction_and_more	2026-09-16 04:30:01.33648+00
20	core	0003_unified_borrower_data	2026-09-16 04:30:02.222693+00
21	core	0004_data_routing_and_exchange	2026-09-16 04:30:02.689722+00
22	core	0005_routing_policy_lender_fields	2026-09-16 04:30:02.750859+00
23	core	0006_four_decimal_places	2026-09-16 04:30:04.228805+00
24	sessions	0001_initial	2026-09-16 04:30:04.40757+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: daire
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 88, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: core_aireputationresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_aireputationresult_id_seq', 1, false);


--
-- Name: core_assessment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_assessment_id_seq', 1, false);


--
-- Name: core_blockchaintransaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_blockchaintransaction_id_seq', 1, false);


--
-- Name: core_borrower_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_borrower_id_seq', 1, false);


--
-- Name: core_borroweraccount_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_borroweraccount_id_seq', 1, false);


--
-- Name: core_borrowerfinancialprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_borrowerfinancialprofile_id_seq', 1, false);


--
-- Name: core_borrowerloan_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_borrowerloan_id_seq', 1, false);


--
-- Name: core_consent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_consent_id_seq', 1, false);


--
-- Name: core_creditfeature_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_creditfeature_id_seq', 1, false);


--
-- Name: core_creditprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_creditprofile_id_seq', 1, false);


--
-- Name: core_dataexchange_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_dataexchange_id_seq', 1, false);


--
-- Name: core_dataroutingpolicy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_dataroutingpolicy_id_seq', 1, true);


--
-- Name: core_integrationrequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_integrationrequest_id_seq', 1, false);


--
-- Name: core_lender_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_lender_id_seq', 1, false);


--
-- Name: core_repaymentrecord_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_repaymentrecord_id_seq', 1, false);


--
-- Name: core_smartcontractresult_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.core_smartcontractresult_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 22, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: daire
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 24, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: core_aireputationresult core_aireputationresult_assessment_id_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_aireputationresult
    ADD CONSTRAINT core_aireputationresult_assessment_id_key UNIQUE (assessment_id);


--
-- Name: core_aireputationresult core_aireputationresult_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_aireputationresult
    ADD CONSTRAINT core_aireputationresult_pkey PRIMARY KEY (id);


--
-- Name: core_assessment core_assessment_assessment_reference_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_assessment
    ADD CONSTRAINT core_assessment_assessment_reference_key UNIQUE (assessment_reference);


--
-- Name: core_assessment core_assessment_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_assessment
    ADD CONSTRAINT core_assessment_pkey PRIMARY KEY (id);


--
-- Name: core_blockchaintransaction core_blockchaintransaction_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_blockchaintransaction
    ADD CONSTRAINT core_blockchaintransaction_pkey PRIMARY KEY (id);


--
-- Name: core_blockchaintransaction core_blockchaintransaction_transaction_hash_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_blockchaintransaction
    ADD CONSTRAINT core_blockchaintransaction_transaction_hash_key UNIQUE (transaction_hash);


--
-- Name: core_borrower core_borrower_borrower_reference_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrower
    ADD CONSTRAINT core_borrower_borrower_reference_key UNIQUE (borrower_reference);


--
-- Name: core_borrower core_borrower_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrower
    ADD CONSTRAINT core_borrower_pkey PRIMARY KEY (id);


--
-- Name: core_borroweraccount core_borroweraccount_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borroweraccount
    ADD CONSTRAINT core_borroweraccount_pkey PRIMARY KEY (id);


--
-- Name: core_borrowerfinancialprofile core_borrowerfinancialprofile_borrower_id_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrowerfinancialprofile
    ADD CONSTRAINT core_borrowerfinancialprofile_borrower_id_key UNIQUE (borrower_id);


--
-- Name: core_borrowerfinancialprofile core_borrowerfinancialprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrowerfinancialprofile
    ADD CONSTRAINT core_borrowerfinancialprofile_pkey PRIMARY KEY (id);


--
-- Name: core_borrowerloan core_borrowerloan_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrowerloan
    ADD CONSTRAINT core_borrowerloan_pkey PRIMARY KEY (id);


--
-- Name: core_consent core_consent_consent_id_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_consent
    ADD CONSTRAINT core_consent_consent_id_key UNIQUE (consent_id);


--
-- Name: core_consent core_consent_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_consent
    ADD CONSTRAINT core_consent_pkey PRIMARY KEY (id);


--
-- Name: core_creditfeature core_creditfeature_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_creditfeature
    ADD CONSTRAINT core_creditfeature_pkey PRIMARY KEY (id);


--
-- Name: core_creditprofile core_creditprofile_integration_request_id_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_creditprofile
    ADD CONSTRAINT core_creditprofile_integration_request_id_key UNIQUE (integration_request_id);


--
-- Name: core_creditprofile core_creditprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_creditprofile
    ADD CONSTRAINT core_creditprofile_pkey PRIMARY KEY (id);


--
-- Name: core_dataexchange core_dataexchange_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_dataexchange
    ADD CONSTRAINT core_dataexchange_pkey PRIMARY KEY (id);


--
-- Name: core_dataroutingpolicy core_dataroutingpolicy_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_dataroutingpolicy
    ADD CONSTRAINT core_dataroutingpolicy_pkey PRIMARY KEY (id);


--
-- Name: core_dataroutingpolicy core_dataroutingpolicy_policy_id_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_dataroutingpolicy
    ADD CONSTRAINT core_dataroutingpolicy_policy_id_key UNIQUE (policy_id);


--
-- Name: core_integrationrequest core_integrationrequest_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_integrationrequest
    ADD CONSTRAINT core_integrationrequest_pkey PRIMARY KEY (id);


--
-- Name: core_integrationrequest core_integrationrequest_request_reference_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_integrationrequest
    ADD CONSTRAINT core_integrationrequest_request_reference_key UNIQUE (request_reference);


--
-- Name: core_lender core_lender_lender_id_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_lender
    ADD CONSTRAINT core_lender_lender_id_key UNIQUE (lender_id);


--
-- Name: core_lender core_lender_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_lender
    ADD CONSTRAINT core_lender_pkey PRIMARY KEY (id);


--
-- Name: core_repaymentrecord core_repaymentrecord_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_repaymentrecord
    ADD CONSTRAINT core_repaymentrecord_pkey PRIMARY KEY (id);


--
-- Name: core_smartcontractresult core_smartcontractresult_assessment_id_key; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_smartcontractresult
    ADD CONSTRAINT core_smartcontractresult_assessment_id_key UNIQUE (assessment_id);


--
-- Name: core_smartcontractresult core_smartcontractresult_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_smartcontractresult
    ADD CONSTRAINT core_smartcontractresult_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: core_borroweraccount unique_borrower_account_per_lender; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borroweraccount
    ADD CONSTRAINT unique_borrower_account_per_lender UNIQUE (borrower_id, lender_id, account_reference);


--
-- Name: core_borrowerloan unique_borrower_loan_per_lender; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrowerloan
    ADD CONSTRAINT unique_borrower_loan_per_lender UNIQUE (borrower_id, lender_id, loan_id);


--
-- Name: core_creditfeature unique_credit_feature; Type: CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_creditfeature
    ADD CONSTRAINT unique_credit_feature UNIQUE (profile_id, name);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: core_assessment_assessment_reference_9ebaffd0_like; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_assessment_assessment_reference_9ebaffd0_like ON public.core_assessment USING btree (assessment_reference varchar_pattern_ops);


--
-- Name: core_assessment_borrower_id_84f09148; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_assessment_borrower_id_84f09148 ON public.core_assessment USING btree (borrower_id);


--
-- Name: core_blockchaintransaction_assessment_id_06434de8; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_blockchaintransaction_assessment_id_06434de8 ON public.core_blockchaintransaction USING btree (assessment_id);


--
-- Name: core_blockchaintransaction_transaction_hash_41ac0374_like; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_blockchaintransaction_transaction_hash_41ac0374_like ON public.core_blockchaintransaction USING btree (transaction_hash varchar_pattern_ops);


--
-- Name: core_borrower_borrower_reference_871188d0_like; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_borrower_borrower_reference_871188d0_like ON public.core_borrower USING btree (borrower_reference varchar_pattern_ops);


--
-- Name: core_borroweraccount_borrower_id_c720b783; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_borroweraccount_borrower_id_c720b783 ON public.core_borroweraccount USING btree (borrower_id);


--
-- Name: core_borroweraccount_lender_id_e3f1692d; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_borroweraccount_lender_id_e3f1692d ON public.core_borroweraccount USING btree (lender_id);


--
-- Name: core_borrowerloan_borrower_id_19510b8f; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_borrowerloan_borrower_id_19510b8f ON public.core_borrowerloan USING btree (borrower_id);


--
-- Name: core_borrowerloan_lender_id_e88ce3b9; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_borrowerloan_lender_id_e88ce3b9 ON public.core_borrowerloan USING btree (lender_id);


--
-- Name: core_borrowerloan_source_account_id_fe019b20; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_borrowerloan_source_account_id_fe019b20 ON public.core_borrowerloan USING btree (source_account_id);


--
-- Name: core_consent_borrower_id_dab0a554; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_consent_borrower_id_dab0a554 ON public.core_consent USING btree (borrower_id);


--
-- Name: core_consent_consent_id_b5e26e21_like; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_consent_consent_id_b5e26e21_like ON public.core_consent USING btree (consent_id varchar_pattern_ops);


--
-- Name: core_consent_lender_id_fc13cde4; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_consent_lender_id_fc13cde4 ON public.core_consent USING btree (lender_id);


--
-- Name: core_creditfeature_profile_id_3acd00b3; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_creditfeature_profile_id_3acd00b3 ON public.core_creditfeature USING btree (profile_id);


--
-- Name: core_creditprofile_borrower_id_c5ed51a4; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_creditprofile_borrower_id_c5ed51a4 ON public.core_creditprofile USING btree (borrower_id);


--
-- Name: core_dataexchange_assessment_id_f0b0dda7; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_dataexchange_assessment_id_f0b0dda7 ON public.core_dataexchange USING btree (assessment_id);


--
-- Name: core_dataexchange_borrower_id_6086df03; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_dataexchange_borrower_id_6086df03 ON public.core_dataexchange USING btree (borrower_id);


--
-- Name: core_dataexchange_lender_id_b3643b0a; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_dataexchange_lender_id_b3643b0a ON public.core_dataexchange USING btree (lender_id);


--
-- Name: core_dataexchange_policy_id_938ebafa; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_dataexchange_policy_id_938ebafa ON public.core_dataexchange USING btree (policy_id);


--
-- Name: core_dataroutingpolicy_policy_id_09306785_like; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_dataroutingpolicy_policy_id_09306785_like ON public.core_dataroutingpolicy USING btree (policy_id varchar_pattern_ops);


--
-- Name: core_integrationrequest_borrower_id_70878b0c; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_integrationrequest_borrower_id_70878b0c ON public.core_integrationrequest USING btree (borrower_id);


--
-- Name: core_integrationrequest_consent_id_d710e650; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_integrationrequest_consent_id_d710e650 ON public.core_integrationrequest USING btree (consent_id);


--
-- Name: core_integrationrequest_lender_id_9cbe9a4a; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_integrationrequest_lender_id_9cbe9a4a ON public.core_integrationrequest USING btree (lender_id);


--
-- Name: core_lender_lender_id_4d8e669c_like; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_lender_lender_id_4d8e669c_like ON public.core_lender USING btree (lender_id varchar_pattern_ops);


--
-- Name: core_repaymentrecord_borrower_id_5db223df; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_repaymentrecord_borrower_id_5db223df ON public.core_repaymentrecord USING btree (borrower_id);


--
-- Name: core_repaymentrecord_lender_id_725a83f2; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_repaymentrecord_lender_id_725a83f2 ON public.core_repaymentrecord USING btree (lender_id);


--
-- Name: core_repaymentrecord_loan_id_67500382; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX core_repaymentrecord_loan_id_67500382 ON public.core_repaymentrecord USING btree (loan_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: daire
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_aireputationresult core_aireputationres_assessment_id_04e91798_fk_core_asse; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_aireputationresult
    ADD CONSTRAINT core_aireputationres_assessment_id_04e91798_fk_core_asse FOREIGN KEY (assessment_id) REFERENCES public.core_assessment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_assessment core_assessment_borrower_id_84f09148_fk_core_borrower_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_assessment
    ADD CONSTRAINT core_assessment_borrower_id_84f09148_fk_core_borrower_id FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_blockchaintransaction core_blockchaintrans_assessment_id_06434de8_fk_core_asse; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_blockchaintransaction
    ADD CONSTRAINT core_blockchaintrans_assessment_id_06434de8_fk_core_asse FOREIGN KEY (assessment_id) REFERENCES public.core_assessment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_borroweraccount core_borroweraccount_borrower_id_c720b783_fk_core_borrower_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borroweraccount
    ADD CONSTRAINT core_borroweraccount_borrower_id_c720b783_fk_core_borrower_id FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_borroweraccount core_borroweraccount_lender_id_e3f1692d_fk_core_lender_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borroweraccount
    ADD CONSTRAINT core_borroweraccount_lender_id_e3f1692d_fk_core_lender_id FOREIGN KEY (lender_id) REFERENCES public.core_lender(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_borrowerfinancialprofile core_borrowerfinanci_borrower_id_820fae3e_fk_core_borr; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrowerfinancialprofile
    ADD CONSTRAINT core_borrowerfinanci_borrower_id_820fae3e_fk_core_borr FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_borrowerloan core_borrowerloan_borrower_id_19510b8f_fk_core_borrower_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrowerloan
    ADD CONSTRAINT core_borrowerloan_borrower_id_19510b8f_fk_core_borrower_id FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_borrowerloan core_borrowerloan_lender_id_e88ce3b9_fk_core_lender_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrowerloan
    ADD CONSTRAINT core_borrowerloan_lender_id_e88ce3b9_fk_core_lender_id FOREIGN KEY (lender_id) REFERENCES public.core_lender(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_borrowerloan core_borrowerloan_source_account_id_fe019b20_fk_core_borr; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_borrowerloan
    ADD CONSTRAINT core_borrowerloan_source_account_id_fe019b20_fk_core_borr FOREIGN KEY (source_account_id) REFERENCES public.core_borroweraccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_consent core_consent_borrower_id_dab0a554_fk_core_borrower_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_consent
    ADD CONSTRAINT core_consent_borrower_id_dab0a554_fk_core_borrower_id FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_consent core_consent_lender_id_fc13cde4_fk_core_lender_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_consent
    ADD CONSTRAINT core_consent_lender_id_fc13cde4_fk_core_lender_id FOREIGN KEY (lender_id) REFERENCES public.core_lender(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_creditfeature core_creditfeature_profile_id_3acd00b3_fk_core_creditprofile_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_creditfeature
    ADD CONSTRAINT core_creditfeature_profile_id_3acd00b3_fk_core_creditprofile_id FOREIGN KEY (profile_id) REFERENCES public.core_creditprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_creditprofile core_creditprofile_borrower_id_c5ed51a4_fk_core_borrower_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_creditprofile
    ADD CONSTRAINT core_creditprofile_borrower_id_c5ed51a4_fk_core_borrower_id FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_creditprofile core_creditprofile_integration_request__720da656_fk_core_inte; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_creditprofile
    ADD CONSTRAINT core_creditprofile_integration_request__720da656_fk_core_inte FOREIGN KEY (integration_request_id) REFERENCES public.core_integrationrequest(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_dataexchange core_dataexchange_assessment_id_f0b0dda7_fk_core_assessment_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_dataexchange
    ADD CONSTRAINT core_dataexchange_assessment_id_f0b0dda7_fk_core_assessment_id FOREIGN KEY (assessment_id) REFERENCES public.core_assessment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_dataexchange core_dataexchange_borrower_id_6086df03_fk_core_borrower_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_dataexchange
    ADD CONSTRAINT core_dataexchange_borrower_id_6086df03_fk_core_borrower_id FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_dataexchange core_dataexchange_lender_id_b3643b0a_fk_core_lender_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_dataexchange
    ADD CONSTRAINT core_dataexchange_lender_id_b3643b0a_fk_core_lender_id FOREIGN KEY (lender_id) REFERENCES public.core_lender(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_dataexchange core_dataexchange_policy_id_938ebafa_fk_core_data; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_dataexchange
    ADD CONSTRAINT core_dataexchange_policy_id_938ebafa_fk_core_data FOREIGN KEY (policy_id) REFERENCES public.core_dataroutingpolicy(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_integrationrequest core_integrationrequ_borrower_id_70878b0c_fk_core_borr; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_integrationrequest
    ADD CONSTRAINT core_integrationrequ_borrower_id_70878b0c_fk_core_borr FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_integrationrequest core_integrationrequest_consent_id_d710e650_fk_core_consent_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_integrationrequest
    ADD CONSTRAINT core_integrationrequest_consent_id_d710e650_fk_core_consent_id FOREIGN KEY (consent_id) REFERENCES public.core_consent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_integrationrequest core_integrationrequest_lender_id_9cbe9a4a_fk_core_lender_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_integrationrequest
    ADD CONSTRAINT core_integrationrequest_lender_id_9cbe9a4a_fk_core_lender_id FOREIGN KEY (lender_id) REFERENCES public.core_lender(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_repaymentrecord core_repaymentrecord_borrower_id_5db223df_fk_core_borrower_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_repaymentrecord
    ADD CONSTRAINT core_repaymentrecord_borrower_id_5db223df_fk_core_borrower_id FOREIGN KEY (borrower_id) REFERENCES public.core_borrower(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_repaymentrecord core_repaymentrecord_lender_id_725a83f2_fk_core_lender_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_repaymentrecord
    ADD CONSTRAINT core_repaymentrecord_lender_id_725a83f2_fk_core_lender_id FOREIGN KEY (lender_id) REFERENCES public.core_lender(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_repaymentrecord core_repaymentrecord_loan_id_67500382_fk_core_borrowerloan_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_repaymentrecord
    ADD CONSTRAINT core_repaymentrecord_loan_id_67500382_fk_core_borrowerloan_id FOREIGN KEY (loan_id) REFERENCES public.core_borrowerloan(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_smartcontractresult core_smartcontractre_assessment_id_b8d9a80e_fk_core_asse; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.core_smartcontractresult
    ADD CONSTRAINT core_smartcontractre_assessment_id_b8d9a80e_fk_core_asse FOREIGN KEY (assessment_id) REFERENCES public.core_assessment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: daire
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict saOqgpNiyIdJo9e5Ju5bRw6ljfZiNNUZjGECjhROd7dDVzkxF7YIWKOKMFktDKc

