/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface DaireHandshakeInterface extends Interface {
    getFunction(nameOrSignature: "DOC_REF" | "STAGE" | "SYSTEM" | "ageInSeconds" | "deployedAt" | "deployer" | "info" | "lastNote" | "ping" | "pingCount"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deployed" | "Ping"): EventFragment;

    encodeFunctionData(functionFragment: 'DOC_REF', values?: undefined): string;
encodeFunctionData(functionFragment: 'STAGE', values?: undefined): string;
encodeFunctionData(functionFragment: 'SYSTEM', values?: undefined): string;
encodeFunctionData(functionFragment: 'ageInSeconds', values?: undefined): string;
encodeFunctionData(functionFragment: 'deployedAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'deployer', values?: undefined): string;
encodeFunctionData(functionFragment: 'info', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastNote', values?: undefined): string;
encodeFunctionData(functionFragment: 'ping', values: [string]): string;
encodeFunctionData(functionFragment: 'pingCount', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DOC_REF', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STAGE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SYSTEM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ageInSeconds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'info', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastNote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ping', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pingCount', data: BytesLike): Result;
  }

  
    export namespace DeployedEvent {
      export type InputTuple = [deployer: AddressLike, timestamp: BigNumberish, stage: string];
      export type OutputTuple = [deployer: string, timestamp: bigint, stage: string];
      export interface OutputObject {deployer: string, timestamp: bigint, stage: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PingEvent {
      export type InputTuple = [caller: AddressLike, newCount: BigNumberish, note: string];
      export type OutputTuple = [caller: string, newCount: bigint, note: string];
      export interface OutputObject {caller: string, newCount: bigint, note: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DaireHandshake extends BaseContract {
    
    connect(runner?: ContractRunner | null): DaireHandshake;
    waitForDeployment(): Promise<this>;

    interface: DaireHandshakeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DOC_REF: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    STAGE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SYSTEM: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ageInSeconds: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deployedAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deployer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    info: TypedContractMethod<
      [],
      [[string, string, string, bigint, bigint, string] & {system: string, stage: string, who: string, when: bigint, pings: bigint, note: string }],
      'view'
    >
    

    
    lastNote: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ping: TypedContractMethod<
      [note: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    pingCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DOC_REF'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'STAGE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SYSTEM'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ageInSeconds'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deployedAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deployer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'info'): TypedContractMethod<
      [],
      [[string, string, string, bigint, bigint, string] & {system: string, stage: string, who: string, when: bigint, pings: bigint, note: string }],
      'view'
    >;
getFunction(nameOrSignature: 'lastNote'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ping'): TypedContractMethod<
      [note: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pingCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'Deployed'): TypedContractEvent<DeployedEvent.InputTuple, DeployedEvent.OutputTuple, DeployedEvent.OutputObject>;
getEvent(key: 'Ping'): TypedContractEvent<PingEvent.InputTuple, PingEvent.OutputTuple, PingEvent.OutputObject>;

    filters: {
      
      'Deployed(address,uint256,string)': TypedContractEvent<DeployedEvent.InputTuple, DeployedEvent.OutputTuple, DeployedEvent.OutputObject>;
      Deployed: TypedContractEvent<DeployedEvent.InputTuple, DeployedEvent.OutputTuple, DeployedEvent.OutputObject>;
    

      'Ping(address,uint256,string)': TypedContractEvent<PingEvent.InputTuple, PingEvent.OutputTuple, PingEvent.OutputObject>;
      Ping: TypedContractEvent<PingEvent.InputTuple, PingEvent.OutputTuple, PingEvent.OutputObject>;
    
    };
  }