/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace DaireCreditScore {
      
    export type FeaturesStruct = {historyMonths: BigNumberish, behaviourEventCount: BigNumberish, repaymentRecordCount: BigNumberish, verifiedSourceCount: BigNumberish, onTimeRatioBps: BigNumberish, maxDaysLate: BigNumberish, missedCount: BigNumberish, onTimeStreak: BigNumberish, activeMonthsBps: BigNumberish, regularMonthsBps: BigNumberish, balanceStabilityBps: BigNumberish, defaultCount: BigNumberish, completedCount: BigNumberish, utilizationBps: BigNumberish, activeLenderCount: BigNumberish, trendBps: BigNumberish, volatilityBps: BigNumberish, monthsSinceAdverse: BigNumberish, distinctSourceCount: BigNumberish, meanCorroborationX100: BigNumberish, openConflictCount: BigNumberish}

    export type FeaturesStructOutput = [historyMonths: bigint, behaviourEventCount: bigint, repaymentRecordCount: bigint, verifiedSourceCount: bigint, onTimeRatioBps: bigint, maxDaysLate: bigint, missedCount: bigint, onTimeStreak: bigint, activeMonthsBps: bigint, regularMonthsBps: bigint, balanceStabilityBps: bigint, defaultCount: bigint, completedCount: bigint, utilizationBps: bigint, activeLenderCount: bigint, trendBps: bigint, volatilityBps: bigint, monthsSinceAdverse: bigint, distinctSourceCount: bigint, meanCorroborationX100: bigint, openConflictCount: bigint] & {historyMonths: bigint, behaviourEventCount: bigint, repaymentRecordCount: bigint, verifiedSourceCount: bigint, onTimeRatioBps: bigint, maxDaysLate: bigint, missedCount: bigint, onTimeStreak: bigint, activeMonthsBps: bigint, regularMonthsBps: bigint, balanceStabilityBps: bigint, defaultCount: bigint, completedCount: bigint, utilizationBps: bigint, activeLenderCount: bigint, trendBps: bigint, volatilityBps: bigint, monthsSinceAdverse: bigint, distinctSourceCount: bigint, meanCorroborationX100: bigint, openConflictCount: bigint }
  

    export type AssessmentStruct = {score: BigNumberish, d1: BigNumberish, d2: BigNumberish, d3: BigNumberish, d4: BigNumberish, d5: BigNumberish, band: BigNumberish, assessedAt: BigNumberish, version: BigNumberish, submittedBy: AddressLike}

    export type AssessmentStructOutput = [score: bigint, d1: bigint, d2: bigint, d3: bigint, d4: bigint, d5: bigint, band: bigint, assessedAt: bigint, version: bigint, submittedBy: string] & {score: bigint, d1: bigint, d2: bigint, d3: bigint, d4: bigint, d5: bigint, band: bigint, assessedAt: bigint, version: bigint, submittedBy: string }
  
    }

  export interface DaireCreditScoreInterface extends Interface {
    getFunction(nameOrSignature: "BPS" | "DIMENSION_FLOOR" | "DOC_REF" | "MAX_SCORE" | "MIN_BEHAVIOUR_EVENTS" | "MIN_HISTORY_MONTHS" | "MIN_REPAYMENT_RECORDS" | "MIN_SCORE" | "MIN_VERIFIED_SOURCES" | "MISSING_EVENTS" | "MISSING_HISTORY" | "MISSING_REPAYMENTS" | "MISSING_VERIFIED" | "NEVER" | "RULESET_VERSION" | "SYSTEM" | "W_D1" | "W_D2" | "W_D3" | "W_D4" | "W_D5" | "adversePenalty" | "authorizedHubs" | "checkSufficiency" | "explainMissing" | "getAssessment" | "getDimensions" | "getFullHistory" | "getHistoryAt" | "getScore" | "historyLength" | "makeBorrowerRef" | "owner" | "previewScore" | "riskBandOf" | "scoreD1" | "scoreD2" | "scoreD3" | "scoreD4" | "scoreD5" | "setHub" | "setUseSubmittedBand" | "submitCalculatedScore" | "submitFeatures" | "totalAssessments" | "totalInsufficient" | "transferOwnership" | "useSubmittedBand"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DimensionsRecorded" | "HubAuthorized" | "InsufficientEvidence" | "OwnerTransferred" | "ScoreCalculated" | "ScoreRecorded" | "UseSubmittedBandToggled"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'DIMENSION_FLOOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'DOC_REF', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SCORE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_BEHAVIOUR_EVENTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_HISTORY_MONTHS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_REPAYMENT_RECORDS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_SCORE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_VERIFIED_SOURCES', values?: undefined): string;
encodeFunctionData(functionFragment: 'MISSING_EVENTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MISSING_HISTORY', values?: undefined): string;
encodeFunctionData(functionFragment: 'MISSING_REPAYMENTS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MISSING_VERIFIED', values?: undefined): string;
encodeFunctionData(functionFragment: 'NEVER', values?: undefined): string;
encodeFunctionData(functionFragment: 'RULESET_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'SYSTEM', values?: undefined): string;
encodeFunctionData(functionFragment: 'W_D1', values?: undefined): string;
encodeFunctionData(functionFragment: 'W_D2', values?: undefined): string;
encodeFunctionData(functionFragment: 'W_D3', values?: undefined): string;
encodeFunctionData(functionFragment: 'W_D4', values?: undefined): string;
encodeFunctionData(functionFragment: 'W_D5', values?: undefined): string;
encodeFunctionData(functionFragment: 'adversePenalty', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'authorizedHubs', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'checkSufficiency', values: [DaireCreditScore.FeaturesStruct]): string;
encodeFunctionData(functionFragment: 'explainMissing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAssessment', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getDimensions', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getFullHistory', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getHistoryAt', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getScore', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'historyLength', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'makeBorrowerRef', values: [string, string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'previewScore', values: [DaireCreditScore.FeaturesStruct]): string;
encodeFunctionData(functionFragment: 'riskBandOf', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'scoreD1', values: [DaireCreditScore.FeaturesStruct]): string;
encodeFunctionData(functionFragment: 'scoreD2', values: [DaireCreditScore.FeaturesStruct]): string;
encodeFunctionData(functionFragment: 'scoreD3', values: [DaireCreditScore.FeaturesStruct]): string;
encodeFunctionData(functionFragment: 'scoreD4', values: [DaireCreditScore.FeaturesStruct]): string;
encodeFunctionData(functionFragment: 'scoreD5', values: [DaireCreditScore.FeaturesStruct]): string;
encodeFunctionData(functionFragment: 'setHub', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setUseSubmittedBand', values: [boolean]): string;
encodeFunctionData(functionFragment: 'submitCalculatedScore', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitFeatures', values: [BytesLike, DaireCreditScore.FeaturesStruct]): string;
encodeFunctionData(functionFragment: 'totalAssessments', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalInsufficient', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'useSubmittedBand', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DIMENSION_FLOOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DOC_REF', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SCORE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_BEHAVIOUR_EVENTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_HISTORY_MONTHS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_REPAYMENT_RECORDS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_SCORE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_VERIFIED_SOURCES', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MISSING_EVENTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MISSING_HISTORY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MISSING_REPAYMENTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MISSING_VERIFIED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'NEVER', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'RULESET_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SYSTEM', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'W_D1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'W_D2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'W_D3', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'W_D4', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'W_D5', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adversePenalty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedHubs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkSufficiency', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'explainMissing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAssessment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDimensions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getFullHistory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getHistoryAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'historyLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'makeBorrowerRef', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'riskBandOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'scoreD1', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'scoreD2', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'scoreD3', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'scoreD4', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'scoreD5', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setHub', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUseSubmittedBand', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitCalculatedScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitFeatures', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAssessments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalInsufficient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'useSubmittedBand', data: BytesLike): Result;
  }

  
    export namespace DimensionsRecordedEvent {
      export type InputTuple = [borrowerRef: BytesLike, version: BigNumberish, d1: BigNumberish, d2: BigNumberish, d3: BigNumberish, d4: BigNumberish, d5: BigNumberish];
      export type OutputTuple = [borrowerRef: string, version: bigint, d1: bigint, d2: bigint, d3: bigint, d4: bigint, d5: bigint];
      export interface OutputObject {borrowerRef: string, version: bigint, d1: bigint, d2: bigint, d3: bigint, d4: bigint, d5: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace HubAuthorizedEvent {
      export type InputTuple = [hub: AddressLike, allowed: boolean];
      export type OutputTuple = [hub: string, allowed: boolean];
      export interface OutputObject {hub: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InsufficientEvidenceEvent {
      export type InputTuple = [borrowerRef: BytesLike, hub: AddressLike, missingMask: BigNumberish];
      export type OutputTuple = [borrowerRef: string, hub: string, missingMask: bigint];
      export interface OutputObject {borrowerRef: string, hub: string, missingMask: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerTransferredEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike];
      export type OutputTuple = [from: string, to: string];
      export interface OutputObject {from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScoreCalculatedEvent {
      export type InputTuple = [borrowerRef: BytesLike, hub: AddressLike, score: BigNumberish, band: BigNumberish, version: BigNumberish, assessedAt: BigNumberish];
      export type OutputTuple = [borrowerRef: string, hub: string, score: bigint, band: bigint, version: bigint, assessedAt: bigint];
      export interface OutputObject {borrowerRef: string, hub: string, score: bigint, band: bigint, version: bigint, assessedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ScoreRecordedEvent {
      export type InputTuple = [borrowerRef: BytesLike, hub: AddressLike, finalScore: BigNumberish, band: BigNumberish, version: BigNumberish, recordedAt: BigNumberish];
      export type OutputTuple = [borrowerRef: string, hub: string, finalScore: bigint, band: bigint, version: bigint, recordedAt: bigint];
      export interface OutputObject {borrowerRef: string, hub: string, finalScore: bigint, band: bigint, version: bigint, recordedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UseSubmittedBandToggledEvent {
      export type InputTuple = [enabled: boolean];
      export type OutputTuple = [enabled: boolean];
      export interface OutputObject {enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DaireCreditScore extends BaseContract {
    
    connect(runner?: ContractRunner | null): DaireCreditScore;
    waitForDeployment(): Promise<this>;

    interface: DaireCreditScoreInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DIMENSION_FLOOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DOC_REF: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_SCORE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_BEHAVIOUR_EVENTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_HISTORY_MONTHS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_REPAYMENT_RECORDS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_SCORE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_VERIFIED_SOURCES: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MISSING_EVENTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MISSING_HISTORY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MISSING_REPAYMENTS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MISSING_VERIFIED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    NEVER: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    RULESET_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    SYSTEM: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    W_D1: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    W_D2: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    W_D3: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    W_D4: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    W_D5: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    adversePenalty: TypedContractMethod<
      [monthsSince: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    authorizedHubs: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    checkSufficiency: TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >
    

    
    explainMissing: TypedContractMethod<
      [missingMask: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getAssessment: TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [DaireCreditScore.AssessmentStructOutput],
      'view'
    >
    

    
    getDimensions: TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {d1: bigint, d2: bigint, d3: bigint, d4: bigint, d5: bigint }],
      'view'
    >
    

    
    getFullHistory: TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [DaireCreditScore.AssessmentStructOutput[]],
      'view'
    >
    

    
    getHistoryAt: TypedContractMethod<
      [borrowerRef: BytesLike, index: BigNumberish, ],
      [DaireCreditScore.AssessmentStructOutput],
      'view'
    >
    

    
    getScore: TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [[bigint, bigint, bigint, bigint, boolean] & {score: bigint, band: bigint, assessedAt: bigint, version: bigint, exists: boolean }],
      'view'
    >
    

    
    historyLength: TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    makeBorrowerRef: TypedContractMethod<
      [identityHash: string, salt: string, ],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    previewScore: TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {score: bigint, d1: bigint, d2: bigint, d3: bigint, d4: bigint, d5: bigint, band: bigint, missingMask: bigint }],
      'view'
    >
    

    
    riskBandOf: TypedContractMethod<
      [score: BigNumberish, minDimension: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    scoreD1: TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >
    

    
    scoreD2: TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >
    

    
    scoreD3: TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >
    

    
    scoreD4: TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >
    

    
    scoreD5: TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >
    

    
    setHub: TypedContractMethod<
      [hub: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setUseSubmittedBand: TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    submitCalculatedScore: TypedContractMethod<
      [borrowerRef: BytesLike, finalScore: BigNumberish, d1: BigNumberish, d2: BigNumberish, d3: BigNumberish, d4: BigNumberish, d5: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    submitFeatures: TypedContractMethod<
      [borrowerRef: BytesLike, f: DaireCreditScore.FeaturesStruct, ],
      [[bigint, bigint, bigint] & {score: bigint, band: bigint, missingMask: bigint }],
      'nonpayable'
    >
    

    
    totalAssessments: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalInsufficient: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    useSubmittedBand: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DIMENSION_FLOOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DOC_REF'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SCORE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_BEHAVIOUR_EVENTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_HISTORY_MONTHS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_REPAYMENT_RECORDS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_SCORE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_VERIFIED_SOURCES'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MISSING_EVENTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MISSING_HISTORY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MISSING_REPAYMENTS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MISSING_VERIFIED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'NEVER'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'RULESET_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'SYSTEM'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'W_D1'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'W_D2'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'W_D3'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'W_D4'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'W_D5'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'adversePenalty'): TypedContractMethod<
      [monthsSince: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedHubs'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'checkSufficiency'): TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'explainMissing'): TypedContractMethod<
      [missingMask: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAssessment'): TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [DaireCreditScore.AssessmentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDimensions'): TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [[bigint, bigint, bigint, bigint, bigint] & {d1: bigint, d2: bigint, d3: bigint, d4: bigint, d5: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getFullHistory'): TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [DaireCreditScore.AssessmentStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getHistoryAt'): TypedContractMethod<
      [borrowerRef: BytesLike, index: BigNumberish, ],
      [DaireCreditScore.AssessmentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getScore'): TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [[bigint, bigint, bigint, bigint, boolean] & {score: bigint, band: bigint, assessedAt: bigint, version: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'historyLength'): TypedContractMethod<
      [borrowerRef: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'makeBorrowerRef'): TypedContractMethod<
      [identityHash: string, salt: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'previewScore'): TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {score: bigint, d1: bigint, d2: bigint, d3: bigint, d4: bigint, d5: bigint, band: bigint, missingMask: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'riskBandOf'): TypedContractMethod<
      [score: BigNumberish, minDimension: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'scoreD1'): TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'scoreD2'): TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'scoreD3'): TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'scoreD4'): TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'scoreD5'): TypedContractMethod<
      [f: DaireCreditScore.FeaturesStruct, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setHub'): TypedContractMethod<
      [hub: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUseSubmittedBand'): TypedContractMethod<
      [enabled: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitCalculatedScore'): TypedContractMethod<
      [borrowerRef: BytesLike, finalScore: BigNumberish, d1: BigNumberish, d2: BigNumberish, d3: BigNumberish, d4: BigNumberish, d5: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitFeatures'): TypedContractMethod<
      [borrowerRef: BytesLike, f: DaireCreditScore.FeaturesStruct, ],
      [[bigint, bigint, bigint] & {score: bigint, band: bigint, missingMask: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalAssessments'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalInsufficient'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'useSubmittedBand'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;

    getEvent(key: 'DimensionsRecorded'): TypedContractEvent<DimensionsRecordedEvent.InputTuple, DimensionsRecordedEvent.OutputTuple, DimensionsRecordedEvent.OutputObject>;
getEvent(key: 'HubAuthorized'): TypedContractEvent<HubAuthorizedEvent.InputTuple, HubAuthorizedEvent.OutputTuple, HubAuthorizedEvent.OutputObject>;
getEvent(key: 'InsufficientEvidence'): TypedContractEvent<InsufficientEvidenceEvent.InputTuple, InsufficientEvidenceEvent.OutputTuple, InsufficientEvidenceEvent.OutputObject>;
getEvent(key: 'OwnerTransferred'): TypedContractEvent<OwnerTransferredEvent.InputTuple, OwnerTransferredEvent.OutputTuple, OwnerTransferredEvent.OutputObject>;
getEvent(key: 'ScoreCalculated'): TypedContractEvent<ScoreCalculatedEvent.InputTuple, ScoreCalculatedEvent.OutputTuple, ScoreCalculatedEvent.OutputObject>;
getEvent(key: 'ScoreRecorded'): TypedContractEvent<ScoreRecordedEvent.InputTuple, ScoreRecordedEvent.OutputTuple, ScoreRecordedEvent.OutputObject>;
getEvent(key: 'UseSubmittedBandToggled'): TypedContractEvent<UseSubmittedBandToggledEvent.InputTuple, UseSubmittedBandToggledEvent.OutputTuple, UseSubmittedBandToggledEvent.OutputObject>;

    filters: {
      
      'DimensionsRecorded(bytes32,uint32,uint8,uint8,uint8,uint8,uint8)': TypedContractEvent<DimensionsRecordedEvent.InputTuple, DimensionsRecordedEvent.OutputTuple, DimensionsRecordedEvent.OutputObject>;
      DimensionsRecorded: TypedContractEvent<DimensionsRecordedEvent.InputTuple, DimensionsRecordedEvent.OutputTuple, DimensionsRecordedEvent.OutputObject>;
    

      'HubAuthorized(address,bool)': TypedContractEvent<HubAuthorizedEvent.InputTuple, HubAuthorizedEvent.OutputTuple, HubAuthorizedEvent.OutputObject>;
      HubAuthorized: TypedContractEvent<HubAuthorizedEvent.InputTuple, HubAuthorizedEvent.OutputTuple, HubAuthorizedEvent.OutputObject>;
    

      'InsufficientEvidence(bytes32,address,uint8)': TypedContractEvent<InsufficientEvidenceEvent.InputTuple, InsufficientEvidenceEvent.OutputTuple, InsufficientEvidenceEvent.OutputObject>;
      InsufficientEvidence: TypedContractEvent<InsufficientEvidenceEvent.InputTuple, InsufficientEvidenceEvent.OutputTuple, InsufficientEvidenceEvent.OutputObject>;
    

      'OwnerTransferred(address,address)': TypedContractEvent<OwnerTransferredEvent.InputTuple, OwnerTransferredEvent.OutputTuple, OwnerTransferredEvent.OutputObject>;
      OwnerTransferred: TypedContractEvent<OwnerTransferredEvent.InputTuple, OwnerTransferredEvent.OutputTuple, OwnerTransferredEvent.OutputObject>;
    

      'ScoreCalculated(bytes32,address,uint16,uint8,uint32,uint32)': TypedContractEvent<ScoreCalculatedEvent.InputTuple, ScoreCalculatedEvent.OutputTuple, ScoreCalculatedEvent.OutputObject>;
      ScoreCalculated: TypedContractEvent<ScoreCalculatedEvent.InputTuple, ScoreCalculatedEvent.OutputTuple, ScoreCalculatedEvent.OutputObject>;
    

      'ScoreRecorded(bytes32,address,uint16,uint8,uint32,uint32)': TypedContractEvent<ScoreRecordedEvent.InputTuple, ScoreRecordedEvent.OutputTuple, ScoreRecordedEvent.OutputObject>;
      ScoreRecorded: TypedContractEvent<ScoreRecordedEvent.InputTuple, ScoreRecordedEvent.OutputTuple, ScoreRecordedEvent.OutputObject>;
    

      'UseSubmittedBandToggled(bool)': TypedContractEvent<UseSubmittedBandToggledEvent.InputTuple, UseSubmittedBandToggledEvent.OutputTuple, UseSubmittedBandToggledEvent.OutputObject>;
      UseSubmittedBandToggled: TypedContractEvent<UseSubmittedBandToggledEvent.InputTuple, UseSubmittedBandToggledEvent.OutputTuple, UseSubmittedBandToggledEvent.OutputObject>;
    
    };
  }