# Generated by Codebuff for NIDA identity-keyed borrower merges

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_borrower_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrower",
            name="nida_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Cross-lender borrower identity evidence (NIDA number, national ID). Unique for borrower merging instead of lender-specific borrower_reference.",
                max_length=64,
            ),
        ),
    ]
