# Generated by Django 5.2.17 on 2026-09-26 14:41

import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# core.migrations.0004_data_routing_and_exchange
# core.migrations.0005_routing_policy_lender_fields
# core.migrations.0012_numeric_ids


def create_default_policy(apps, schema_editor):
    Policy = apps.get_model("core", "DataRoutingPolicy")
    Policy.objects.get_or_create(
        policy_id="DEFAULT-CREDIT-ROUTING",
        defaults={
            "name": "Default credit scoring policy",
            "ai_fields": [
                "active_loan_count", "completed_loan_count", "defaulted_loan_count",
                "total_outstanding_debt", "on_time_payment_ratio", "missed_payment_count",
                "late_payment_count", "max_days_overdue", "transaction_frequency",
                "income_frequency", "balance_stability",
            ],
            "blockchain_fields": [
                "active_loan_count", "completed_loan_count", "defaulted_loan_count",
                "total_outstanding_debt", "on_time_payment_ratio", "missed_payment_count",
                "late_payment_count", "max_days_overdue",
            ],
            "active": True,
            "version": "1.0.0",
        },
    )

def set_default_lender_fields(apps, schema_editor):
    DataRoutingPolicy = apps.get_model("core", "DataRoutingPolicy")
    policy, _ = DataRoutingPolicy.objects.get_or_create(
        policy_id="DEFAULT-CREDIT-ROUTING",
        defaults={"lender_fields": []},
    )
    policy.lender_fields = []
    policy.save(update_fields=["lender_fields", "updated_at"])

def strip_prefixes(apps, schema_editor):
    Borrower = apps.get_model("core", "Borrower")
    for b in Borrower.objects.all():
        ref = b.borrower_reference
        if isinstance(ref, str) and ref[:2].upper() in {"BR", "RW", "10", "11"}:
            numeric = "".join(ch for ch in ref if ch.isdigit())
            if numeric:
                b.borrower_reference = numeric
                b.save(update_fields=["borrower_reference"])

def add_prefixes(apps, schema_editor):
    Borrower = apps.get_model("core", "Borrower")
    for b in Borrower.objects.all():
        ref = b.borrower_reference
        if isinstance(ref, str) and ref.isdigit() and not ref.startswith(("BR", "RW")):
            b.borrower_reference = "BR-" + ref
            b.save(update_fields=["borrower_reference"])

class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_aireputationresult_blockchaintransaction_and_more'), ('core', '0003_unified_borrower_data'), ('core', '0004_data_routing_and_exchange'), ('core', '0005_routing_policy_lender_fields'), ('core', '0006_four_decimal_places'), ('core', '0007_borrower_is_active'), ('core', '0008_data_quality_and_score_explanation'), ('core', '0009_borrower_name'), ('core', '0010_lender_api_key'), ('core', '0011_lender_broadcast_api_key'), ('core', '0012_numeric_ids'), ('core', '0013_alter_borrower_options')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower_reference', models.CharField(max_length=64, unique=True)),
                ('customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('employment_status', models.CharField(blank=True, max_length=50)),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('business_information', models.JSONField(blank=True, default=dict)),
                ('account_information', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lender_id', models.CharField(max_length=64, unique=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(max_length=100)),
                ('api_base_url', models.URLField()),
                ('api_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DEGRADED', 'Degraded'), ('DISCONNECTED', 'Disconnected')], default='DISCONNECTED', max_length=20)),
                ('authentication_method', models.CharField(default='API_KEY', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_reference', models.CharField(max_length=64, unique=True)),
                ('reputation', models.CharField(blank=True, max_length=30)),
                ('reputation_score', models.DecimalField(decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('behavior_summary', models.TextField(blank=True)),
                ('credit_score', models.PositiveSmallIntegerField(null=True)),
                ('ruleset_version', models.CharField(blank=True, max_length=64)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('blockchain_transaction_hash', models.CharField(blank=True, max_length=255)),
                ('blockchain_block_number', models.PositiveBigIntegerField(null=True)),
                ('verification_status', models.CharField(default='PENDING', max_length=30)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.borrower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_id', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(max_length=255)),
                ('granted_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='core.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='core.lender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.borrower')),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.consent')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIReputationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reputation', models.CharField(max_length=30)),
                ('score', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('risk_level', models.CharField(blank=True, max_length=30)),
                ('behavior_summary', models.TextField(blank=True)),
                ('model_version', models.CharField(max_length=64)),
                ('raw_result', models.JSONField(default=dict)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reputation_result', to='core.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('network', models.CharField(max_length=100)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('verification_data', models.JSONField(default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blockchain_transactions', to='core.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_data', models.JSONField(default=dict)),
                ('source_version', models.CharField(default='1', max_length=64)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_profiles', to='core.borrower')),
                ('integration_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_profile', to='core.integrationrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartContractResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_score', models.PositiveSmallIntegerField()),
                ('ruleset_version', models.CharField(max_length=64)),
                ('contract_address', models.CharField(max_length=255)),
                ('raw_result', models.JSONField(default=dict)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_contract_result', to='core.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('feature_version', models.CharField(default='1', max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.creditprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_credit_feature')],
            },
        ),
        migrations.CreateModel(
            name='BorrowerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_reference', models.CharField(blank=True, default='', max_length=128)),
                ('account_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_accounts', to='core.lender')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('borrower', 'lender', 'account_reference'), name='unique_borrower_account_per_lender')],
            },
        ),
        migrations.CreateModel(
            name='BorrowerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_id', models.CharField(max_length=128)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('loan_date', models.DateField(blank=True, null=True)),
                ('loan_duration_months', models.PositiveIntegerField(default=0)),
                ('interest_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(default='ACTIVE', max_length=30)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrower_loans', to='core.lender')),
                ('source_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.borroweraccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('borrower', 'lender', 'loan_id'), name='unique_borrower_loan_per_lender')],
            },
        ),
        migrations.CreateModel(
            name='RepaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repayment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('days_overdue', models.PositiveIntegerField(default=0)),
                ('missed_payments', models.PositiveIntegerField(default=0)),
                ('late_payments', models.PositiveIntegerField(default=0)),
                ('default_status', models.CharField(blank=True, default='', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_records', to='core.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_records', to='core.lender')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='core.borrowerloan')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_frequency', models.PositiveIntegerField(default=0)),
                ('income_frequency', models.PositiveIntegerField(default=0)),
                ('cash_flow_patterns', models.JSONField(blank=True, default=dict)),
                ('savings', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account_activity', models.JSONField(blank=True, default=dict)),
                ('active_loans', models.PositiveIntegerField(default=0)),
                ('total_outstanding_debt', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('previous_loans', models.PositiveIntegerField(default=0)),
                ('debt_to_income_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='core.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='DataRoutingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('ai_fields', models.JSONField(blank=True, default=list)),
                ('blockchain_fields', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DataExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(choices=[('LENDER', 'Lender'), ('AI', 'Ai'), ('BLOCKCHAIN', 'Blockchain')], max_length=20)),
                ('direction', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull')], max_length=10)),
                ('operation', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='STARTED', max_length=10)),
                ('fields_sent', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_exchanges', to='core.assessment')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_exchanges', to='core.borrower')),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_exchanges', to='core.lender')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='data_exchanges', to='core.dataroutingpolicy')),
            ],
        ),
        migrations.RunPython(
            code=create_default_policy,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='dataroutingpolicy',
            name='lender_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(
            code=set_default_lender_fields,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='borrower',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerloan',
            name='loan_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='borrowerloan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='repaymentrecord',
            name='repayment_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='borrowerfinancialprofile',
            name='savings',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='borrowerfinancialprofile',
            name='total_outstanding_debt',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='borrowerfinancialprofile',
            name='monthly_repayment',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='creditfeature',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AddField(
            model_name='borrower',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='data_conflicts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='score_explanation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assessment',
            name='score_inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dataexchange',
            name='batch_reference',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lender',
            name='api_key_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='lender',
            name='api_key_prefix',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='lender',
            name='broadcast_api_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.RunPython(
            code=strip_prefixes,
            reverse_code=add_prefixes,
        ),
        migrations.AlterModelOptions(
            name='borrower',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
