# Generated by Django 5.2.17 on 2026-09-10 21:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReputationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reputation', models.CharField(max_length=30)),
                ('score', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('risk_level', models.CharField(blank=True, max_length=30)),
                ('behavior_summary', models.TextField(blank=True)),
                ('model_version', models.CharField(max_length=64)),
                ('raw_result', models.JSONField(default=dict)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reputation_result', to='core.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_hash', models.CharField(max_length=255, unique=True)),
                ('network', models.CharField(max_length=100)),
                ('block_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('verification_data', models.JSONField(default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blockchain_transactions', to='core.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_data', models.JSONField(default=dict)),
                ('source_version', models.CharField(default='1', max_length=64)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_profiles', to='core.borrower')),
                ('integration_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_profile', to='core.integrationrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmartContractResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_score', models.PositiveSmallIntegerField()),
                ('ruleset_version', models.CharField(max_length=64)),
                ('contract_address', models.CharField(max_length=255)),
                ('raw_result', models.JSONField(default=dict)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smart_contract_result', to='core.assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=8, max_digits=20)),
                ('feature_version', models.CharField(default='1', max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.creditprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile', 'name'), name='unique_credit_feature')],
            },
        ),
    ]
