# Generated by Django 5.2.17 on 2026-09-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_data_quality_and_score_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
