# Generated by Django 5.2.17 on 2026-09-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_numeric_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
