# Generated by Django 5.2.17 on 2026-09-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0013_alter_borrower_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='nida_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
