# Generated by Django 5.2.17 on 2026-09-26 21:03

from django.db import migrations, models


def _dedupe_nida(apps, schema_editor):
    """Clear any duplicate NIDAs before the unique constraint is added.

    The pre-existing SQLite seed data has no NIDA values, so every borrower
    currently carries an empty NIDA. SQLite's UNIQUE constraint rejects
    multiple empty-string values, so we normalise all empty NIDAs to NULL
    first, then drop duplicate non-null NIDAs (keeping the oldest borrower).
    """
    Borrower = apps.get_model("core", "Borrower")
    db_alias = schema_editor.connection.alias
    # 1) Clear empty NIDAs to NULL — SQLite's unique() rejects multiple '' values.
    Borrower.objects.using(db_alias).filter(nida_number="").update(nida_number=None)
    # 2) Drop duplicates: keep the oldest borrower per nida_number.
    borrowers = Borrower.objects.using(db_alias).order_by("id").all()
    seen = {}
    for b in borrowers:
        if b.nida_number:
            seen.setdefault(b.nida_number, []).append(b)
    for nida, group in seen.items():
        for b in group[1:]:
            b.nida_number = None
            b.save(update_fields=("nida_number",))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_borrower_nida_number"),
    ]

    operations = [
        # Data cleanup: ensure no two borrowers hold the same NIDA before the
        # unique constraint is added.
        migrations.RunPython(_dedupe_nida, migrations.RunPython.noop),
        # Enforce the lender's identity: one central borrower per NIDA.
        migrations.AlterField(
            model_name="borrower",
            name="nida_number",
            field=models.CharField(
                blank=True, default="", max_length=128, unique=True
            ),
        ),
    ]
