# Generated by Django 5.2.17 on 2026-09-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_borrower_nida_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='nida_number',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
    ]
