# Generated by Django 5.2.17 on 2026-09-30 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_borrower_nida_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_reference', models.CharField(blank=True, default='', max_length=64)),
                ('applied_amount', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='TZS', max_length=8)),
                ('purpose', models.CharField(blank=True, default='', max_length=100)),
                ('term_months', models.PositiveIntegerField(default=0)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSESSED', 'Assessed'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='SUBMITTED', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='core.assessment')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='core.borrower')),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='core.lender')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('borrower', 'lender', 'application_reference'), name='unique_loan_application_per_lender')],
            },
        ),
    ]
