# Generated by Django 5.2.17 on 2026-09-10 19:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower_reference', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lender_id', models.CharField(max_length=64, unique=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(max_length=100)),
                ('api_base_url', models.URLField()),
                ('api_status', models.CharField(choices=[('CONNECTED', 'Connected'), ('DEGRADED', 'Degraded'), ('DISCONNECTED', 'Disconnected')], default='DISCONNECTED', max_length=20)),
                ('authentication_method', models.CharField(default='API_KEY', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=80)),
                ('request_reference', models.UUIDField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_reference', models.CharField(max_length=64, unique=True)),
                ('reputation', models.CharField(blank=True, max_length=30)),
                ('reputation_score', models.DecimalField(decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('behavior_summary', models.TextField(blank=True)),
                ('credit_score', models.PositiveSmallIntegerField(null=True)),
                ('ruleset_version', models.CharField(blank=True, max_length=64)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('blockchain_transaction_hash', models.CharField(blank=True, max_length=255)),
                ('blockchain_block_number', models.PositiveBigIntegerField(null=True)),
                ('verification_status', models.CharField(default='PENDING', max_length=30)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.borrower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_id', models.CharField(max_length=64, unique=True)),
                ('purpose', models.CharField(max_length=255)),
                ('granted_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='core.borrower')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='core.lender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='RECEIVED', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.borrower')),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.consent')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
